FROM golang:1.13-alpine

RUN apk add --no-cache \
	git \
	build-base

RUN go get -u golang.org/x/lint/golint \
	&& go get golang.org/x/tools/cmd/goimports \
	&& go get github.com/markbates/pkger/cmd/pkger
