FROM golang:alpine AS build
WORKDIR /go/src/github.com/pinmonl/pinmonl/
COPY ./ ./
RUN apk add --no-cache --virtual .deps build-base git \
  && go get github.com/markbates/pkger/cmd/pkger \
  && make build-exchange \
  && apk del .deps

FROM alpine
WORKDIR /pinmonl/
COPY --from=build /go/src/github.com/pinmonl/pinmonl/releases/exchange /usr/local/bin/pinmonl-exchange
EXPOSE 8080
ENTRYPOINT ["pinmonl-exchange"]
CMD ["server"]
