FROM golang:1.13-alpine

RUN apk add --no-cache \
	git \
	build-base

RUN go get -u golang.org/x/lint/golint \
	&& go get golang.org/x/tools/cmd/goimports \
	&& go get github.com/go-task/task/cmd/task \
	&& go get github.com/gobuffalo/packr/v2/packr2
